In [1]:
import pandas as pd

# Pandas Básico — Manipulación de datos tabulares

## 1. Series y DataFrames

Una Series es una columna — array 1D con etiquetas. Un DataFrame es una tabla — conjunto de Series.

In [3]:
s = pd.Series([10,20,30,40,50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
print(type(s))

<class 'pandas.Series'>

np.array([10, 20, 30]) — solo valores, índice numérico implícito

pd.Series([10, 20, 30]) — valores + índice explícito con etiquetas

In [8]:
s = pd.Series([10,20,30], index = ['manzana', 'pera', 'naranja'])

print(s)

manzana    10
pera       20
naranja    30
dtype: int64

In [10]:
print(s['manzana']) # accedemos ahora por nombre, no por posición como haciamos en los arrays

10

Un DataFrame es simplemente un diccionario de Series. Cada columna es una Series y todas comparten el mismo índice.

DataFrame
├── columna 'producto'  → Series de strings
├── columna 'precio'    → Series de floats
└── columna 'kilos'     → Series de ints

In [15]:
datos = {
    'producto': ['manzana', 'pera', 'naranja', 'fresa'],
    'precio': [1.2,0.8,0.5,2.1],
    'kilos': [100,150,200,80]
}

df = pd.DataFrame(datos)

print(df) # diccionario de series de las que hemos visto
print(type(df))

  producto  precio  kilos
0  manzana     1.2    100
1     pera     0.8    150
2  naranja     0.5    200
3    fresa     2.1     80
<class 'pandas.DataFrame'>

In [17]:
print(df.shape)

(4, 3)

In [18]:
print(df.dtypes)

producto        str
precio      float64
kilos         int64
dtype: object

Y por dentro cada Series es un array de numpy. Es decir:
dict → DataFrame → Series → numpy array

## 2. Cargar datos

In [ ]:
import numpy as np

np.random.seed(42) 
df = pd.DataFrame({
    'nombre': ['Ana', 'Luis', 'María', 'Carlos', 'Elena', 'Pedro', 'Laura', 'Juan', 'Sofía', 'David'],
    'edad': np.random.randint(18, 65, 10),
    'ciudad': np.random.choice(['Madrid', 'Barcelona', 'Valencia', 'Sevilla'], 10),
    'salario': np.random.randint(18000, 60000, 10),
    'departamento': np.random.choice(['Ventas', 'IT', 'RRHH', 'Marketing'], 10),
    'años_empresa': np.random.randint(1, 20, 10)
})

df.to_csv("../datasets/empleados.csv", index=False)
print("Guardado!")
df

Guardado!

   nombre  edad     ciudad  salario departamento  años_empresa
0     Ana    56   Valencia    20433         RRHH            15
1    Luis    46    Sevilla    23311         RRHH            19
2   María    32     Madrid    55819           IT            12
3  Carlos    60    Sevilla    57188    Marketing             3
4   Elena    25    Sevilla    35568    Marketing             5
5   Pedro    38    Sevilla    37769    Marketing            19
6   Laura    56   Valencia    46693    Marketing             7
7    Juan    36  Barcelona    24396         RRHH             9
8   Sofía    40     Madrid    45480           IT             7
9   David    28  Barcelona    59434           IT            18

In [22]:
df = pd.read_csv("../datasets/empleados.csv")

print(df.shape)
df.head()

(10, 6)

   nombre  edad    ciudad  salario departamento  años_empresa
0     Ana    56  Valencia    20433         RRHH            15
1    Luis    46   Sevilla    23311         RRHH            19
2   María    32    Madrid    55819           IT            12
3  Carlos    60   Sevilla    57188    Marketing             3
4   Elena    25   Sevilla    35568    Marketing             5

## 3. Exploración básica

In [24]:
df.head()      # primeras 5 filas

   nombre  edad    ciudad  salario departamento  años_empresa
0     Ana    56  Valencia    20433         RRHH            15
1    Luis    46   Sevilla    23311         RRHH            19
2   María    32    Madrid    55819           IT            12
3  Carlos    60   Sevilla    57188    Marketing             3
4   Elena    25   Sevilla    35568    Marketing             5

In [25]:
df.tail()      # últimas 5 filas

  nombre  edad     ciudad  salario departamento  años_empresa
5  Pedro    38    Sevilla    37769    Marketing            19
6  Laura    56   Valencia    46693    Marketing             7
7   Juan    36  Barcelona    24396         RRHH             9
8  Sofía    40     Madrid    45480           IT             7
9  David    28  Barcelona    59434           IT            18

In [26]:
df.info()      # tipos de datos y nulos

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nombre        10 non-null     str
 1   edad          10 non-null     int64
 2   ciudad        10 non-null     str
 3   salario       10 non-null     int64
 4   departamento  10 non-null     str
 5   años_empresa  10 non-null     int64
dtypes: int64(3), str(3)
memory usage: 612.0 bytes

In [28]:
df.describe()  # estadísticas básicas de las numericas

            edad       salario  años_empresa
count  10.000000     10.000000     10.000000
mean   41.700000  40609.100000     11.400000
std    12.347289  14620.989832      6.040603
min    25.000000  20433.000000      3.000000
25%    33.000000  27189.000000      7.000000
50%    39.000000  41624.500000     10.500000
75%    53.500000  53537.500000     17.250000
max    60.000000  59434.000000     19.000000

In [29]:
df.shape       # filas y columnas
df.columns     # nombres de columnas

Index(['nombre', 'edad', 'ciudad', 'salario', 'departamento', 'años_empresa'], dtype='str')

## 4. Indexing — loc e iloc

In [30]:
df.head()

   nombre  edad    ciudad  salario departamento  años_empresa
0     Ana    56  Valencia    20433         RRHH            15
1    Luis    46   Sevilla    23311         RRHH            19
2   María    32    Madrid    55819           IT            12
3  Carlos    60   Sevilla    57188    Marketing             3
4   Elena    25   Sevilla    35568    Marketing             5

In [ ]:
print(df.loc[0])           # fila con índice 0 interno

nombre               Ana
edad                  56
ciudad          Valencia
salario            20433
departamento        RRHH
años_empresa          15
Name: 0, dtype: object

In [ ]:
print(df.iloc[0])          # primera fila por posición q ves

nombre               Ana
edad                  56
ciudad          Valencia
salario            20433
departamento        RRHH
años_empresa          15
Name: 0, dtype: object

In [ ]:
print(df.loc[0, 'nombre']) # fila 0, columna nombre

Ana

In [34]:
print(df.iloc[0, 1])       # fila 0, columna 1

56

In [35]:
print(df.loc[0:3, 'nombre':'ciudad'])   # filas 0 a 3, columnas nombre hasta ciudad
print(df.iloc[0:3, 0:3])                # filas 0 a 3, columnas 0 a 3

   nombre  edad    ciudad
0     Ana    56  Valencia
1    Luis    46   Sevilla
2   María    32    Madrid
3  Carlos    60   Sevilla
  nombre  edad    ciudad
0    Ana    56  Valencia
1   Luis    46   Sevilla
2  María    32    Madrid

 Una cosa importante — loc es inclusivo en ambos extremos (incluye el 3), iloc es exclusivo al final (no incluye el 3), igual que el slicing de Python.

## 5. Filtrado

In [36]:
# Filtrar empleados con salario mayor de 40000
print(df[df['salario'] > 40000])

   nombre  edad     ciudad  salario departamento  años_empresa
2   María    32     Madrid    55819           IT            12
3  Carlos    60    Sevilla    57188    Marketing             3
6   Laura    56   Valencia    46693    Marketing             7
8   Sofía    40     Madrid    45480           IT             7
9   David    28  Barcelona    59434           IT            18

In [37]:
# Una condición
df[df['salario'] > 40000]

# Dos condiciones — AND
df[(df['salario'] > 40000) & (df['ciudad'] == 'Madrid')]

# Dos condiciones — OR
df[(df['salario'] > 40000) | (df['ciudad'] == 'Madrid')]

# isin — varios valores
df[df['ciudad'].isin(['Madrid', 'Barcelona'])]

# notna — filtrar nulos
df[df['salario'].notna()]

   nombre  edad     ciudad  salario departamento  años_empresa
0     Ana    56   Valencia    20433         RRHH            15
1    Luis    46    Sevilla    23311         RRHH            19
2   María    32     Madrid    55819           IT            12
3  Carlos    60    Sevilla    57188    Marketing             3
4   Elena    25    Sevilla    35568    Marketing             5
5   Pedro    38    Sevilla    37769    Marketing            19
6   Laura    56   Valencia    46693    Marketing             7
7    Juan    36  Barcelona    24396         RRHH             9
8   Sofía    40     Madrid    45480           IT             7
9   David    28  Barcelona    59434           IT            18

In [38]:
# query — forma más limpia de filtrar
df.query("salario > 40000 and ciudad == 'Madrid'")

# ~ — negación
df[~df['ciudad'].isin(['Madrid', 'Barcelona'])]

   nombre  edad    ciudad  salario departamento  años_empresa
0     Ana    56  Valencia    20433         RRHH            15
1    Luis    46   Sevilla    23311         RRHH            19
3  Carlos    60   Sevilla    57188    Marketing             3
4   Elena    25   Sevilla    35568    Marketing             5
5   Pedro    38   Sevilla    37769    Marketing            19
6   Laura    56  Valencia    46693    Marketing             7

## 6. Operaciones básicas

In [39]:
# Añadir columna
df['salario_mensual'] = df['salario'] / 12

# Eliminar columna
df.drop(columns=['salario_mensual'], inplace=True)

# Renombrar columna
df.rename(columns={'nombre': 'name'}, inplace=True)

# Ordenar
df.sort_values('salario', ascending=False)

# Valores únicos
df['ciudad'].unique()
df['ciudad'].value_counts()

# Aplicar función
df['salario'].apply(lambda x: x * 1.1)

# Agrupar
df.groupby('ciudad')['salario'].mean()

# Nulos
df.isnull().sum()
df.dropna()
df.fillna(0)

     name  edad     ciudad  salario departamento  años_empresa
0     Ana    56   Valencia    20433         RRHH            15
1    Luis    46    Sevilla    23311         RRHH            19
2   María    32     Madrid    55819           IT            12
3  Carlos    60    Sevilla    57188    Marketing             3
4   Elena    25    Sevilla    35568    Marketing             5
5   Pedro    38    Sevilla    37769    Marketing            19
6   Laura    56   Valencia    46693    Marketing             7
7    Juan    36  Barcelona    24396         RRHH             9
8   Sofía    40     Madrid    45480           IT             7
9   David    28  Barcelona    59434           IT            18

## Ejercicios

In [40]:
import pandas as pd
import numpy as np

np.random.seed(42)
n = 200

df = pd.DataFrame({
    'nombre': np.random.choice(['Ana', 'Luis', 'María', 'Carlos', 'Elena', 'Pedro', 'Laura', 'Juan', 'Sofía', 'David'], n),
    'edad': np.random.randint(18, 65, n),
    'ciudad': np.random.choice(['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao'], n),
    'salario': np.random.randint(18000, 80000, n),
    'departamento': np.random.choice(['Ventas', 'IT', 'RRHH', 'Marketing', 'Finanzas'], n),
    'años_empresa': np.random.randint(1, 25, n),
    'satisfaccion': np.random.choice([1, 2, 3, 4, 5], n),
    'remoto': np.random.choice([True, False], n),
    'formacion': np.random.choice(['Bachillerato', 'FP', 'Grado', 'Master', 'Doctorado'], n),
    'ventas_anuales': np.random.randint(0, 500000, n)
})

# Introducir algunos nulos
df.loc[np.random.choice(n, 20), 'salario'] = np.nan
df.loc[np.random.choice(n, 15), 'satisfaccion'] = np.nan

df.to_csv("../datasets/empleados_rico.csv", index=False)
print("Guardado!")
df.head()

Guardado!

,nombre,edad,ciudad,salario,departamento,años_empresa,satisfaccion,remoto,formacion,ventas_anuales
0,Laura,39,Madrid,38652.0,IT,3,3.0,False,Doctorado,157661
1,Carlos,28,Valencia,22748.0,RRHH,1,2.0,True,Bachillerato,161087
2,Juan,33,Sevilla,39233.0,RRHH,8,1.0,False,Bachillerato,160081
3,Elena,50,Barcelona,27435.0,Marketing,22,3.0,False,Master,345453
4,Laura,26,Barcelona,NaN,IT,8,2.0,False,Doctorado,388590

### Ejercicio 1 — Exploración
¿Cuántos nulos hay por columna? ¿Qué porcentaje representa cada uno sobre el total de filas?

In [43]:
df_ejers = pd.read_csv('../datasets/empleados_rico.csv')

df_ejers.head()

,nombre,edad,ciudad,salario,departamento,años_empresa,satisfaccion,remoto,formacion,ventas_anuales
0,Laura,39,Madrid,38652.0,IT,3,3.0,False,Doctorado,157661
1,Carlos,28,Valencia,22748.0,RRHH,1,2.0,True,Bachillerato,161087
2,Juan,33,Sevilla,39233.0,RRHH,8,1.0,False,Bachillerato,160081
3,Elena,50,Barcelona,27435.0,Marketing,22,3.0,False,Master,345453
4,Laura,26,Barcelona,NaN,IT,8,2.0,False,Doctorado,388590

In [49]:
df_ejers.isnull().sum()

nombre             0
edad               0
ciudad             0
salario           20
departamento       0
años_empresa       0
satisfaccion      14
remoto             0
formacion          0
ventas_anuales     0
dtype: int64

In [50]:
df_ejers.isna().sum() # otra forma de obtener lo mismo

nombre             0
edad               0
ciudad             0
salario           20
departamento       0
años_empresa       0
satisfaccion      14
remoto             0
formacion          0
ventas_anuales     0
dtype: int64

In [52]:
df_ejers.info() # se puede suponer cuantos nulos hay por columna teniendo en cuenta el df_ejers.shape

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nombre          200 non-null    str
 1   edad            200 non-null    int64
 2   ciudad          200 non-null    str
 3   salario         180 non-null    float64
 4   departamento    200 non-null    str
 5   años_empresa    200 non-null    int64
 6   satisfaccion    186 non-null    float64
 7   remoto          200 non-null    bool
 8   formacion       200 non-null    str
 9   ventas_anuales  200 non-null    int64
dtypes: bool(1), float64(2), int64(3), str(4)
memory usage: 14.4 KB

In [57]:
df_ejers.isna().mean()
df_ejers.isna().mean() * 100 # multiplicamos la boolean mask por 100

nombre             0.0
edad               0.0
ciudad             0.0
salario           10.0
departamento       0.0
años_empresa       0.0
satisfaccion       7.0
remoto             0.0
formacion          0.0
ventas_anuales     0.0
dtype: float64

### Ejercicio 2 — Filtrado
Filtra los empleados que trabajan en remoto, tienen Master o Doctorado y cobran más de 50.000€. ¿Cuántos son?

In [65]:
df_ejers.head()

,nombre,edad,ciudad,salario,departamento,años_empresa,satisfaccion,remoto,formacion,ventas_anuales
0,Laura,39,Madrid,38652.0,IT,3,3.0,False,Doctorado,157661
1,Carlos,28,Valencia,22748.0,RRHH,1,2.0,True,Bachillerato,161087
2,Juan,33,Sevilla,39233.0,RRHH,8,1.0,False,Bachillerato,160081
3,Elena,50,Barcelona,27435.0,Marketing,22,3.0,False,Master,345453
4,Laura,26,Barcelona,NaN,IT,8,2.0,False,Doctorado,388590

In [73]:
resultados = df_ejers[(df_ejers['remoto'] == True) & (df_ejers['formacion'].isin(['Master','Doctorado'])) & (df_ejers['salario']>50000)]
resultados.shape[0]

29

df_ejers['remoto'] == True se puede simplificar a df_ejers['remoto'] directamente ya que es booleano

In [74]:
resultados = df_ejers[(df_ejers['remoto']) & (df_ejers['formacion'].isin(['Master','Doctorado'])) & (df_ejers['salario']>50000)]
resultados.shape[0]

29

### Ejercicio 3 — Operaciones
Crea una columna `salario_por_año` que divida el salario entre los años en la empresa. Ordena el DataFrame por esta columna de mayor a menor.

In [76]:
df_ejers.head()

,nombre,edad,ciudad,salario,departamento,años_empresa,satisfaccion,remoto,formacion,ventas_anuales
0,Laura,39,Madrid,38652.0,IT,3,3.0,False,Doctorado,157661
1,Carlos,28,Valencia,22748.0,RRHH,1,2.0,True,Bachillerato,161087
2,Juan,33,Sevilla,39233.0,RRHH,8,1.0,False,Bachillerato,160081
3,Elena,50,Barcelona,27435.0,Marketing,22,3.0,False,Master,345453
4,Laura,26,Barcelona,NaN,IT,8,2.0,False,Doctorado,388590

In [80]:
df_ejers['salario_por_año'] = df_ejers['salario'] / df_ejers['años_empresa']
df_ejers.head()

df_ejers = df_ejers.sort_values(by='salario_por_año',ascending=False)

In [81]:
df_ejers.head()

,nombre,edad,ciudad,salario,departamento,años_empresa,satisfaccion,remoto,formacion,ventas_anuales,salario_por_año
26,David,45,Valencia,64196.0,Marketing,1,3.0,True,Doctorado,245198,64196.0
52,Carlos,28,Madrid,62597.0,IT,1,2.0,True,Bachillerato,154470,62597.0
190,Carlos,49,Sevilla,60808.0,Finanzas,1,1.0,False,Bachillerato,420706,60808.0
29,Carlos,48,Bilbao,54395.0,Finanzas,1,5.0,True,Doctorado,488533,54395.0
60,Carlos,52,Sevilla,52121.0,Marketing,1,4.0,True,Grado,9078,52121.0

### Ejercicio 4 — Groupby
Calcula la media de salario y de satisfacción por departamento. ¿Qué departamento paga más? ¿Y el más satisfecho?

In [87]:
df_ejers.groupby(by = 'departamento')[['salario','satisfaccion']].mean()

                   salario  satisfaccion
departamento
Finanzas      52285.290323      2.833333
IT            52207.947368      2.697674
Marketing     50986.777778      2.694444
RRHH          48546.731707      3.282051
Ventas        48308.441176      2.973684

In [104]:
df_ejers.groupby('departamento')['salario'].mean().idxmax()

'Finanzas'

In [103]:
df_ejers.groupby('departamento')['satisfaccion'].mean().idxmax()

'RRHH'

### Ejercicio 5 — Groupby avanzado
Agrupa por ciudad y departamento a la vez y calcula el salario máximo y mínimo de cada combinación.

In [106]:
df_ejers.groupby(by= ['ciudad', 'departamento'])['salario'].max()
df_ejers.groupby(by= ['ciudad', 'departamento'])['salario'].min()

ciudad     departamento
Barcelona  Finanzas        35640.0
           IT              19252.0
           Marketing       27435.0
           RRHH            31216.0
           Ventas          37255.0
Bilbao     Finanzas        18504.0
           IT              21330.0
           Marketing       18384.0
           RRHH            28916.0
           Ventas          18667.0
Madrid     Finanzas        28136.0
           IT              20105.0
           Marketing       22158.0
           RRHH            18404.0
           Ventas          28344.0
Sevilla    Finanzas        25114.0
           IT              19015.0
           Marketing       18009.0
           RRHH            24938.0
           Ventas          26427.0
Valencia   Finanzas        55892.0
           IT              21636.0
           Marketing       33106.0
           RRHH            22748.0
           Ventas          36017.0
Name: salario, dtype: float64

In [107]:
# se puede hacer con una sola linea
df_ejers.groupby(['ciudad', 'departamento'])['salario'].agg(['max', 'min'])

                            max      min
ciudad    departamento
Barcelona Finanzas      75043.0  35640.0
          IT            79480.0  19252.0
          Marketing     79877.0  27435.0
          RRHH          79642.0  31216.0
          Ventas        62238.0  37255.0
Bilbao    Finanzas      67922.0  18504.0
          IT            76425.0  21330.0
          Marketing     76141.0  18384.0
          RRHH          65198.0  28916.0
          Ventas        79629.0  18667.0
Madrid    Finanzas      71330.0  28136.0
          IT            79813.0  20105.0
          Marketing     67407.0  22158.0
          RRHH          78381.0  18404.0
          Ventas        79529.0  28344.0
Sevilla   Finanzas      60808.0  25114.0
          IT            74178.0  19015.0
          Marketing     55732.0  18009.0
          RRHH          65926.0  24938.0
          Ventas        68612.0  26427.0
Valencia  Finanzas      73971.0  55892.0
          IT            78100.0  21636.0
          Marketing     75091.0  33106.0
          RRHH          74570.0  22748.0
          Ventas        63445.0  36017.0

### Ejercicio 6 — Apply
Crea una columna `nivel_seniority` basada en años_empresa: menos de 3 años → 'Junior', entre 3 y 10 → 'Mid', más de 10 → 'Senior'.

In [111]:
df_ejers['nivel_seniority']= df_ejers['años_empresa'].apply(lambda x: 'Junior' if x<3 else ('Mid' if x<=10 else 'Senior'))

In [112]:
df_ejers.head()

,nombre,edad,ciudad,salario,departamento,años_empresa,satisfaccion,remoto,formacion,ventas_anuales,salario_por_año,nivel_seniority
26,David,45,Valencia,64196.0,Marketing,1,3.0,True,Doctorado,245198,64196.0,Junior
52,Carlos,28,Madrid,62597.0,IT,1,2.0,True,Bachillerato,154470,62597.0,Junior
190,Carlos,49,Sevilla,60808.0,Finanzas,1,1.0,False,Bachillerato,420706,60808.0,Junior
29,Carlos,48,Bilbao,54395.0,Finanzas,1,5.0,True,Doctorado,488533,54395.0,Junior
60,Carlos,52,Sevilla,52121.0,Marketing,1,4.0,True,Grado,9078,52121.0,Junior

### Ejercicio 7 — Nulos
Rellena los nulos de salario con la media del salario de su mismo departamento (no la media global).

In [115]:
df_ejers['salario'].isna().sum()

np.int64(20)

In [118]:
df_ejers.groupby('departamento')['salario'].mean()

departamento
Finanzas     52285.290323
IT           52207.947368
Marketing    50986.777778
RRHH         48546.731707
Ventas       48308.441176
Name: salario, dtype: float64

In [132]:
df_ejers['salario'] = df_ejers['salario'].fillna(df_ejers.groupby('departamento')['salario'].transform('mean')) # rellenas los nulos con lo que corresponda de la media del transform

La clave es transform — en vez de devolver una media por grupo, devuelve el valor de la media para cada fila según su departamento

### Ejercicio 8 — Filtrado complejo
Encuentra los empleados cuyo salario está por encima de la media de su ciudad y además tienen satisfacción mayor o igual a 4.

In [ ]:
# 1 media de salarios por ciudad para cada registro con la funcion transform
media_ciudad = df_ejers.groupby('ciudad')['salario'].transform('mean')

df_ejers[(df_ejers['salario']> media_ciudad) & (df_ejers['satisfaccion']>=4)]

,nombre,edad,ciudad,salario,departamento,años_empresa,satisfaccion,remoto,formacion,ventas_anuales,salario_por_año,nivel_seniority
29,Carlos,48,Bilbao,54395.000000,Finanzas,1,5.0,True,Doctorado,488533,54395.000000,Junior
60,Carlos,52,Sevilla,52121.000000,Marketing,1,4.0,True,Grado,9078,52121.000000,Junior
157,María,62,Barcelona,73752.000000,Marketing,2,5.0,True,FP,361403,36876.000000,Junior
81,Sofía,50,Barcelona,79480.000000,IT,4,5.0,True,Bachillerato,396605,19870.000000,Mid
12,Juan,43,Barcelona,60918.000000,Ventas,5,5.0,True,Bachillerato,51195,12183.600000,Mid
132,María,41,Sevilla,58034.000000,Finanzas,5,5.0,True,Doctorado,265064,11606.800000,Mid
37,Laura,18,Barcelona,79642.000000,RRHH,8,4.0,True,Doctorado,194555,9955.250000,Mid
187,David,21,Madrid,78381.000000,RRHH,8,4.0,False,Master,260116,9797.625000,Mid
189,Laura,62,Sevilla,55626.000000,Ventas,7,5.0,False,Bachillerato,319200,7946.571429,Mid
20,Elena,57,Bilbao,52299.000000,Marketing,8,4.0,False,Doctorado,206376,6537.375000,Mid
111,María,52,Valencia,74570.000000,RRHH,12,4.0,False,Doctorado,83186,6214.166667,Senior
182,Ana,25,Valencia,55131.000000,Ventas,9,5.0,False,Grado,390411,6125.666667,Mid
128,Laura,48,Bilbao,64540.000000,Finanzas,11,4.0,True,Doctorado,367505,5867.272727,Senior
103,Laura,52,Madrid,67407.000000,Marketing,13,4.0,True,Master,373706,5185.153846,Senior
50,María,50,Valencia,70736.000000,Finanzas,15,4.0,True,Grado,108737,4715.733333,Senior
100,Luis,22,Valencia,63445.000000,Ventas,14,5.0,False,Master,253627,4531.785714,Senior
71,Elena,50,Sevilla,64427.000000,RRHH,15,4.0,False,Doctorado,117832,4295.133333,Senior
177,Luis,23,Barcelona,79877.000000,Marketing,21,5.0,True,Doctorado,291570,3803.666667,Senior
120,David,38,Bilbao,64318.000000,IT,17,4.0,False,Grado,110198,3783.411765,Senior
91,Ana,44,Barcelona,75043.000000,Finanzas,20,5.0,True,FP,459651,3752.150000,Senior
178,Luis,32,Barcelona,61125.000000,IT,17,4.0,True,Master,279922,3595.588235,Senior
49,Juan,41,Barcelona,70638.000000,RRHH,20,5.0,True,Bachillerato,314470,3531.900000,Senior
85,Juan,63,Valencia,65605.000000,IT,19,4.0,False,Master,24826,3452.894737,Senior
116,David,63,Madrid,79813.000000,IT,24,5.0,False,Master,445795,3325.541667,Senior
175,Ana,39,Barcelona,67401.000000,Finanzas,22,4.0,True,Master,438566,3063.681818,Senior
171,Ana,40,Bilbao,65198.000000,RRHH,24,4.0,True,Doctorado,289102,2716.583333,Senior
170,María,49,Madrid,54187.000000,RRHH,21,5.0,False,Bachillerato,43585,2580.333333,Senior
33,María,24,Sevilla,55678.000000,RRHH,23,4.0,False,Doctorado,336585,2420.782609,Senior
27,María,42,Bilbao,52285.290323,Finanzas,23,5.0,False,FP,467535,NaN,Senior
61,Pedro,42,Sevilla,52207.947368,IT,4,4.0,False,Master,418219,NaN,Mid
88,Juan,55,Bilbao,48546.731707,RRHH,4,5.0,True,Grado,229834,NaN,Mid
144,Ana,50,Bilbao,48546.731707,RRHH,21,4.0,False,Master,491872,NaN,Senior

### Ejercicio 9 — value_counts y ranking
¿Cuál es la combinación de ciudad y formación más común? Muestra el top 5.

In [135]:
df_ejers[['ciudad','formacion']].value_counts().head(5)

ciudad     formacion
Bilbao     Doctorado    15
           Grado        12
Barcelona  Grado        11
Madrid     FP           10
Barcelona  Master       10
Name: count, dtype: int64

### Ejercicio 10 — Resumen final
Crea un DataFrame resumen con: número de empleados, salario medio, satisfacción media y total de ventas anuales por departamento, ordenado por salario medio descendente.

In [141]:
df_ejers.groupby('departamento').agg(
    numero_empleados=('salario', 'count'),
    salario_medio=('salario', 'mean'),
    satisfaccion_media=('satisfaccion', 'mean'),
    total_ventas=('ventas_anuales', 'sum')
).sort_values('salario_medio', ascending=False)

,numero_empleados,salario_medio,satisfaccion_media,total_ventas
departamento,,,,
Finanzas,35,52285.290323,2.833333,10554578
IT,45,52207.947368,2.697674,12052136
Marketing,37,50986.777778,2.694444,9062630
RRHH,43,48546.731707,3.282051,10310579
Ventas,40,48308.441176,2.973684,9787984